_BASE_: "mask_rcnn_R_50_FPN_3x.yaml"
DATASETS:
 TRAIN: ("car_train",)
 TEST: ("car_train",)
DATALOADER:
 NUM_WORKERS: 4
 FILTER_EMPTY_ANNOTATIONS: False
MODEL:
 WEIGHTS: "/home/roadzen/ParasWork/PretrainedWeights/dt2/mask_rcnn_R_50_FPN_3x.pkl"
 ROI_HEADS:
  BATCH_SIZE_PER_IMAGE: 128   
  NUM_CLASSES: 196 
  SCORE_THRESH_TEST: 0.01
  NMS_THRESH_TEST: 0.5
  IOU_THRESHOLDS: 
  - 0.5
 RPN:
  NMS_THRESH: 0.5
  IOU_THRESHOLDS:
  - 0.5
  - 0.7
  IN_FEATURES:
  - p3
  - p4
  - p5
  - p6
 ANCHOR_GENERATOR:
  SIZES:
  - - 64
  - - 128
  - - 256
  - - 512
 ROI_MASK_HEAD:
  POOLER_RESOLUTION: 14
 ROI_BOX_HEAD:
  POOLER_RESOLUTION: 7
SOLVER:
 IMS_PER_BATCH: 4
 BASE_LR: 0.0025
 STEPS:
 - 5000
 - 5000
 MAX_ITER: 4000
 CHECKPOINT_PERIOD: 5000
INPUT:
 MIN_SIZE_TRAIN:
 - 448
 MAX_SIZE_TEST: 448
 MAX_SIZE_TRAIN: 448
 MIN_SIZE_TEST: 448 
OUTPUT_DIR: "CarTrainedModels"