_BASE_: "mask_rcnn_R_101_FPN_3x.yaml"
DATASETS:
 TRAIN: ("damage_train",)
 TEST: ("damage_val",)
DATALOADER:
 NUM_WORKERS: 8
 FILTER_EMPTY_ANNOTATIONS: False
MODEL:
 WEIGHTS: "/home/roadzen/ParasWork/detectron2/extAngleDamModels/toUse.pth"
 ROI_HEADS:
  BATCH_SIZE_PER_IMAGE: 128   
  NUM_CLASSES: 4 
  SCORE_THRESH_TEST: 0.01
  NMS_THRESH_TEST: 0.5
  IOU_THRESHOLDS: 
  - 0.5
 RPN:
  NMS_THRESH: 0.5
  IOU_THRESHOLDS:
  - 0.5
  - 0.7
  IN_FEATURES:
  - p2
  - p3
  - p4
  - p5
  - p6
 ANCHOR_GENERATOR:
  SIZES:
  - - 32
  - - 64
  - - 128
  - - 256
  - - 512
 ROI_MASK_HEAD:
  POOLER_RESOLUTION: 28
 ROI_BOX_HEAD:
  POOLER_RESOLUTION: 7
SOLVER:
 IMS_PER_BATCH: 8
 BASE_LR: 0.0025
 STEPS:
 - 100000
 - 150000
 MAX_ITER: 100000
 CHECKPOINT_PERIOD: 50000
INPUT:
 MIN_SIZE_TRAIN:
 - 224
 - 448
 MAX_SIZE_TEST: 448
 MAX_SIZE_TRAIN: 448
 MIN_SIZE_TEST: 448
TEST:
 AUG:
  ENABLED: true
  FLIP: true
  MAX_SIZE: 448
  MIN_SIZES:
   - 448
OUTPUT_DIR: "bigMaskextAngleDamModels"